OK 47 fix movie tile
okkoro/okkoro pull request #12
Opened 2023-01-19 23:17 UTC by dufourmax1738

# Jira Link:

[[Jira: ]()
](https://champlainsaintlambert.atlassian.net/jira/software/projects/OK/boards/55?selectedIssue=OK-47)
# Context

Fixed the movie tile so that it can be clicked on from every page

# Changes

Changed the movie tile href to be an absolute link instead of relative.

2023-01-19 23:27 UTC, ClementCadieux approved these changes
Simple enough fix, well done.

2023-01-20 17:20 UTC, DuncanBH requested changes
Pretty good change, have you checked if this issue exists anywhere else in the website?

2023-01-21 18:00 UTC, dufourmax1738 commented on components/MovieTile.tsx
> +                <Link href={"/movies/" + props.movie.id}>
I could but it doesn't seem necessary so I will not be doing that change

2023-01-21 18:00 UTC, dufourmax1738 commented
> 

I have and did not see any other issue like this

2023-01-21 18:04 UTC, DuncanBH approved these changes

2023-01-21 20:31 UTC, merged